# Generated by Django 4.2.9 on 2024-08-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_suggestedquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedQuestion',
        ),
    ]
