# Generated by Django 5.1 on 2024-08-21 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_delete_suggestedquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
