# Generated by Django 5.1 on 2024-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_questionanswer_fixed_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
