# Generated by Django 5.1.3 on 2024-11-15 01:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_questionanswer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='fixedquestions',
            name='answer',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='fixedquestions',
            name='question',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='unansweredquestion',
            name='question',
            field=models.TextField(max_length=512),
        ),
    ]
