# Generated by Django 5.1.3 on 2024-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_questionanswer_embedding_alter_fixedquestions_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answers',
            field=models.TextField(default=1, max_length=4096),
            preserve_default=False,
        ),
    ]
