# Generated by Django 5.1.3 on 2024-12-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_remove_questionanswer_answer_questionanswer_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='answer_type',
            field=models.CharField(choices=[('single', '????? ?????'), ('multiple', '?????? ??????')], default='single', max_length=10),
        ),
    ]
