# Generated by Django 5.1.3 on 2024-12-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_questionanswer_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
